//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoMVC.ClienteServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/ProjetoWCF.Data.Entities")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AtivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjetoMVC.ClienteServiceReference.Produto[] ProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SobrenomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ativo {
            get {
                return this.AtivoField;
            }
            set {
                if ((this.AtivoField.Equals(value) != true)) {
                    this.AtivoField = value;
                    this.RaisePropertyChanged("Ativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjetoMVC.ClienteServiceReference.Produto[] Produto {
            get {
                return this.ProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoField, value) != true)) {
                    this.ProdutoField = value;
                    this.RaisePropertyChanged("Produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sobrenome {
            get {
                return this.SobrenomeField;
            }
            set {
                if ((object.ReferenceEquals(this.SobrenomeField, value) != true)) {
                    this.SobrenomeField = value;
                    this.RaisePropertyChanged("Sobrenome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/ProjetoWCF.Data.Entities")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjetoMVC.ClienteServiceReference.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisponivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProdutoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjetoMVC.ClienteServiceReference.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Disponivel {
            get {
                return this.DisponivelField;
            }
            set {
                if ((object.ReferenceEquals(this.DisponivelField, value) != true)) {
                    this.DisponivelField = value;
                    this.RaisePropertyChanged("Disponivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdutoId {
            get {
                return this.ProdutoIdField;
            }
            set {
                if ((this.ProdutoIdField.Equals(value) != true)) {
                    this.ProdutoIdField = value;
                    this.RaisePropertyChanged("ProdutoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteServiceReference.IClienteService")]
    public interface IClienteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/FindAll", ReplyAction="http://tempuri.org/IClienteService/FindAllResponse")]
        ProjetoMVC.ClienteServiceReference.Cliente[] FindAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/FindAll", ReplyAction="http://tempuri.org/IClienteService/FindAllResponse")]
        System.Threading.Tasks.Task<ProjetoMVC.ClienteServiceReference.Cliente[]> FindAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Find", ReplyAction="http://tempuri.org/IClienteService/FindResponse")]
        ProjetoMVC.ClienteServiceReference.Cliente Find(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Find", ReplyAction="http://tempuri.org/IClienteService/FindResponse")]
        System.Threading.Tasks.Task<ProjetoMVC.ClienteServiceReference.Cliente> FindAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/New", ReplyAction="http://tempuri.org/IClienteService/NewResponse")]
        ProjetoMVC.ClienteServiceReference.Cliente New(ProjetoMVC.ClienteServiceReference.Cliente produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/New", ReplyAction="http://tempuri.org/IClienteService/NewResponse")]
        System.Threading.Tasks.Task<ProjetoMVC.ClienteServiceReference.Cliente> NewAsync(ProjetoMVC.ClienteServiceReference.Cliente produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Update", ReplyAction="http://tempuri.org/IClienteService/UpdateResponse")]
        ProjetoMVC.ClienteServiceReference.Cliente Update(ProjetoMVC.ClienteServiceReference.Cliente produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Update", ReplyAction="http://tempuri.org/IClienteService/UpdateResponse")]
        System.Threading.Tasks.Task<ProjetoMVC.ClienteServiceReference.Cliente> UpdateAsync(ProjetoMVC.ClienteServiceReference.Cliente produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Delete", ReplyAction="http://tempuri.org/IClienteService/DeleteResponse")]
        ProjetoMVC.ClienteServiceReference.Cliente Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Delete", ReplyAction="http://tempuri.org/IClienteService/DeleteResponse")]
        System.Threading.Tasks.Task<ProjetoMVC.ClienteServiceReference.Cliente> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Detete", ReplyAction="http://tempuri.org/IClienteService/DeteteResponse")]
        ProjetoMVC.ClienteServiceReference.Cliente Detete(ProjetoMVC.ClienteServiceReference.Cliente produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Detete", ReplyAction="http://tempuri.org/IClienteService/DeteteResponse")]
        System.Threading.Tasks.Task<ProjetoMVC.ClienteServiceReference.Cliente> DeteteAsync(ProjetoMVC.ClienteServiceReference.Cliente produto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteServiceChannel : ProjetoMVC.ClienteServiceReference.IClienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<ProjetoMVC.ClienteServiceReference.IClienteService>, ProjetoMVC.ClienteServiceReference.IClienteService {
        
        public ClienteServiceClient() {
        }
        
        public ClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProjetoMVC.ClienteServiceReference.Cliente[] FindAll() {
            return base.Channel.FindAll();
        }
        
        public System.Threading.Tasks.Task<ProjetoMVC.ClienteServiceReference.Cliente[]> FindAllAsync() {
            return base.Channel.FindAllAsync();
        }
        
        public ProjetoMVC.ClienteServiceReference.Cliente Find(int id) {
            return base.Channel.Find(id);
        }
        
        public System.Threading.Tasks.Task<ProjetoMVC.ClienteServiceReference.Cliente> FindAsync(int id) {
            return base.Channel.FindAsync(id);
        }
        
        public ProjetoMVC.ClienteServiceReference.Cliente New(ProjetoMVC.ClienteServiceReference.Cliente produto) {
            return base.Channel.New(produto);
        }
        
        public System.Threading.Tasks.Task<ProjetoMVC.ClienteServiceReference.Cliente> NewAsync(ProjetoMVC.ClienteServiceReference.Cliente produto) {
            return base.Channel.NewAsync(produto);
        }
        
        public ProjetoMVC.ClienteServiceReference.Cliente Update(ProjetoMVC.ClienteServiceReference.Cliente produto) {
            return base.Channel.Update(produto);
        }
        
        public System.Threading.Tasks.Task<ProjetoMVC.ClienteServiceReference.Cliente> UpdateAsync(ProjetoMVC.ClienteServiceReference.Cliente produto) {
            return base.Channel.UpdateAsync(produto);
        }
        
        public ProjetoMVC.ClienteServiceReference.Cliente Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<ProjetoMVC.ClienteServiceReference.Cliente> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public ProjetoMVC.ClienteServiceReference.Cliente Detete(ProjetoMVC.ClienteServiceReference.Cliente produto) {
            return base.Channel.Detete(produto);
        }
        
        public System.Threading.Tasks.Task<ProjetoMVC.ClienteServiceReference.Cliente> DeteteAsync(ProjetoMVC.ClienteServiceReference.Cliente produto) {
            return base.Channel.DeteteAsync(produto);
        }
    }
}
